services:
  # Servicio de base de datos IRIS
  - type: web
    name: iris-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: IRIS_PASSWORD
        value: SYS
    healthCheckPath: /api/movies/test
    
  # Servicio frontend estático  
  - type: web
    name: movie-frontend
    env: static
    buildCommand: echo "Frontend estático"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: API_URL
        fromService:
          name: iris-backend
          type: web
          property: host
